export const SEARCH_ENTRIES = [
  {
    id: 'home',
    title: 'Home',
    description: 'Odun Creative homepage for premium design, web, app and training services.',
    href: '/',
    group: 'Pages',
    category: 'Page',
    icon: '🏠',
    keywords: ['home', 'landing', 'homepage', 'The Odun Design', 'platform', 'services', 'dashboard'],
    tags: ['home', 'landing']
  },
  {
    id: 'about',
    title: 'About',
    description: 'Learn the story behind Odun Creative and our premium client workflows.',
    href: '/about',
    group: 'Pages',
    category: 'Page',
    icon: 'ℹ️',
    keywords: ['about', 'story', 'team', 'experience', 'brand'],
    tags: ['about', 'company']
  },
  {
    id: 'services',
    title: 'Services',
    description: 'Explore premium packages for design, web, app, SEO and training.',
    href: '/services',
    group: 'Pages',
    category: 'Page',
    icon: '🧩',
    keywords: ['services', 'packages', 'offerings', 'pricing', 'order'],
    tags: ['services', 'solutions']
  },
  {
    id: 'portfolio',
    title: 'Portfolio',
    description: 'View selected premium projects that show our design and development work.',
    href: '/portfolio',
    group: 'Pages',
    category: 'Page',
    icon: '📁',
    keywords: ['portfolio', 'projects', 'work', 'case studies'],
    tags: ['portfolio', 'projects']
  },
  {
    id: 'training',
    title: 'Training',
    description: 'Develop new skills in graphic design, web development, app development and UI/UX.',
    href: '/training',
    group: 'Pages',
    category: 'Page',
    icon: '🎓',
    keywords: ['training', 'courses', 'workshops', 'coaching', 'skills'],
    tags: ['training', 'learning']
  },
  {
    id: 'contact',
    title: 'Contact',
    description: 'Get in touch with Odun Creative for briefs, strategy calls, and new projects.',
    href: '/contact',
    group: 'Pages',
    category: 'Page',
    icon: '✉️',
    keywords: ['contact', 'reach out', 'email', 'phone', 'whatsapp'],
    tags: ['contact', 'support']
  },
  {
    id: 'faq',
    title: 'FAQ',
    description: 'Find answers to common questions about orders, accounts and payments.',
    href: '/#faq',
    group: 'Pages',
    category: 'Page',
    icon: '❓',
    keywords: ['faq', 'questions', 'support', 'help'],
    tags: ['faq', 'questions']
  },
  {
    id: 'testimonials',
    title: 'Testimonials',
    description: 'Read client feedback on our premium platform and delivery experience.',
    href: '/#testimonials',
    group: 'Pages',
    category: 'Page',
    icon: '💬',
    keywords: ['testimonials', 'reviews', 'clients', 'feedback'],
    tags: ['reviews', 'clients']
  },
  {
    id: 'graphic-design',
    title: 'Graphic Design',
    description: 'Branding, marketing assets, and visual systems that feel premium.',
    href: '/services#graphic-design',
    group: 'Services',
    category: 'Graphic Design',
    icon: '🎨',
    keywords: ['graphic design', 'branding', 'visual systems', 'marketing assets'],
    tags: ['flyer', 'poster', 'logo', 'business card', 'social media']
  },
  {
    id: 'web-development',
    title: 'Web Development',
    description: 'Websites and portals built for conversion, speed, and scale.',
    href: '/services#web-development',
    group: 'Services',
    category: 'Web Development',
    icon: '🌐',
    keywords: ['website', 'web development', 'landing page', 'ecommerce', 'blog'],
    tags: ['business website', 'portfolio website', 'real estate']
  },
  {
    id: 'app-development',
    title: 'App Development',
    description: 'Mobile and cross-platform apps with dashboard and API integrations.',
    href: '/services#app-development',
    group: 'Services',
    category: 'App Development',
    icon: '📱',
    keywords: ['app', 'mobile', 'android', 'ios', 'cross-platform'],
    tags: ['android', 'ios', 'native', 'cross-platform']
  },
  {
    id: 'seo',
    title: 'SEO',
    description: 'Search engine optimization to improve visibility and website performance.',
    href: '/services#seo',
    group: 'Services',
    category: 'SEO',
    icon: '🔍',
    keywords: ['seo', 'search engine optimization', 'google ranking', 'website optimization', 'technical seo'],
    tags: ['local seo', 'technical seo', 'rankings']
  },
  {
    id: 'training-services',
    title: 'Training',
    description: 'Coaching and workshops for design, development, app delivery and digital skills.',
    href: '/training',
    group: 'Services',
    category: 'Training',
    icon: '📚',
    keywords: ['training', 'courses', 'coaching', 'workshops'],
    tags: ['graphic design', 'web development', 'app development', 'ui/ux']
  },
  {
    id: 'flyer-design',
    title: 'Flyer Design',
    description: 'Eye-catching promotional flyers for digital and print campaigns.',
    href: '/services#graphic-design',
    group: 'Services',
    category: 'Graphic Design',
    icon: '📄',
    keywords: ['flyer', 'flyer design', 'promotional material', 'print design'],
    tags: ['flyer']
  },
  {
    id: 'banner-design',
    title: 'Banner Design',
    description: 'Web and print banners for campaigns, events and promotions.',
    href: '/services#graphic-design',
    group: 'Services',
    category: 'Graphic Design',
    icon: '🖼️',
    keywords: ['banner', 'banner design', 'web banner', 'print banner'],
    tags: ['banner']
  },
  {
    id: 'logo-design',
    title: 'Logo Design',
    description: 'Memorable brand marks and identity systems for premium businesses.',
    href: '/services#graphic-design',
    group: 'Services',
    category: 'Graphic Design',
    icon: '🔷',
    keywords: ['logo', 'logo design', 'brand mark', 'identity'],
    tags: ['logo']
  },
  {
    id: 'social-media-design',
    title: 'Social Media Design',
    description: 'Graphics for social platforms that keep your brand consistent.',
    href: '/services#graphic-design',
    group: 'Services',
    category: 'Graphic Design',
    icon: '📱',
    keywords: ['social media', 'social design', 'instagram', 'facebook'],
    tags: ['social media']
  },
  {
    id: 'business-card',
    title: 'Business Card',
    description: 'Premium business card designs that communicate your brand identity.',
    href: '/services#graphic-design',
    group: 'Services',
    category: 'Graphic Design',
    icon: '💼',
    keywords: ['business card', 'cards', 'print', 'networking'],
    tags: ['business card']
  },
  {
    id: 'brochure',
    title: 'Brochure',
    description: 'Professional marketing brochures for product and service storytelling.',
    href: '/services#graphic-design',
    group: 'Services',
    category: 'Graphic Design',
    icon: '📘',
    keywords: ['brochure', 'booklet', 'marketing collateral', 'print design'],
    tags: ['brochure']
  },
  {
    id: 'poster',
    title: 'Poster',
    description: 'Large-format poster designs for events, launches and promotions.',
    href: '/services#graphic-design',
    group: 'Services',
    category: 'Graphic Design',
    icon: '📌',
    keywords: ['poster', 'print poster', 'event poster', 'marketing poster'],
    tags: ['poster']
  },
  {
    id: 'invitation-card',
    title: 'Invitation Card',
    description: 'Event and celebration invitations with premium visual appeal.',
    href: '/services#graphic-design',
    group: 'Services',
    category: 'Graphic Design',
    icon: '💌',
    keywords: ['invitation', 'invitation card', 'event invite', 'celebration'],
    tags: ['invitation card']
  },
  {
    id: 'book-cover',
    title: 'Book Cover',
    description: 'High-impact book cover design for print and digital publishing.',
    href: '/services#graphic-design',
    group: 'Services',
    category: 'Graphic Design',
    icon: '📚',
    keywords: ['book cover', 'cover design', 'publishing', 'ebook'],
    tags: ['book cover']
  },
  {
    id: 'packaging',
    title: 'Packaging',
    description: 'Product packaging concepts designed for shelf standout and clarity.',
    href: '/services#graphic-design',
    group: 'Services',
    category: 'Graphic Design',
    icon: '📦',
    keywords: ['packaging', 'package design', 'product packaging'],
    tags: ['packaging']
  },
  {
    id: 'business-website',
    title: 'Business Website',
    description: 'Professional business websites built for conversion and lead generation.',
    href: '/services#web-development',
    group: 'Services',
    category: 'Web Development',
    icon: '🏢',
    keywords: ['business website', 'business site', 'corporate website'],
    tags: ['business website']
  },
  {
    id: 'portfolio-website',
    title: 'Portfolio Website',
    description: 'Showcase your best work with a polished portfolio website.',
    href: '/services#web-development',
    group: 'Services',
    category: 'Web Development',
    icon: '🖥️',
    keywords: ['portfolio website', 'portfolio', 'showcase'],
    tags: ['portfolio website']
  },
  {
    id: 'ecommerce',
    title: 'E-commerce',
    description: 'Online storefronts and marketplaces designed to convert customers.',
    href: '/services#web-development',
    group: 'Services',
    category: 'Web Development',
    icon: '🛒',
    keywords: ['ecommerce', 'online store', 'shop website'],
    tags: ['e-commerce']
  },
  {
    id: 'school-website',
    title: 'School Website',
    description: 'Education websites built for admissions, events and campus communication.',
    href: '/services#web-development',
    group: 'Services',
    category: 'Web Development',
    icon: '🏫',
    keywords: ['school website', 'education site', 'school portal'],
    tags: ['school website']
  },
  {
    id: 'ngo-website',
    title: 'NGO Website',
    description: 'Non-profit and charity websites designed to attract donors and members.',
    href: '/services#web-development',
    group: 'Services',
    category: 'Web Development',
    icon: '🤝',
    keywords: ['ngo website', 'non-profit website', 'charity site'],
    tags: ['ngo website']
  },
  {
    id: 'landing-page',
    title: 'Landing Page',
    description: 'High-converting landing pages for campaigns and product launches.',
    href: '/services#web-development',
    group: 'Services',
    category: 'Web Development',
    icon: '🧲',
    keywords: ['landing page', 'conversion', 'campaign landing page'],
    tags: ['landing page']
  },
  {
    id: 'blog-website',
    title: 'Blog Website',
    description: 'Content-first websites built to publish stories, guides and news.',
    href: '/services#web-development',
    group: 'Services',
    category: 'Web Development',
    icon: '📝',
    keywords: ['blog website', 'blogging', 'content site'],
    tags: ['blog website']
  },
  {
    id: 'company-website',
    title: 'Company Website',
    description: 'Corporate websites that support brand positioning and trust.',
    href: '/services#web-development',
    group: 'Services',
    category: 'Web Development',
    icon: '🏢',
    keywords: ['company website', 'corporate site', 'business presence'],
    tags: ['company website']
  },
  {
    id: 'real-estate-website',
    title: 'Real Estate Website',
    description: 'Property showcase websites for agencies and brokers.',
    href: '/services#web-development',
    group: 'Services',
    category: 'Web Development',
    icon: '🏘️',
    keywords: ['real estate website', 'property site', 'listing website'],
    tags: ['real estate website']
  },
  {
    id: 'booking-website',
    title: 'Booking Website',
    description: 'Reservation and booking websites for services and experiences.',
    href: '/services#web-development',
    group: 'Services',
    category: 'Web Development',
    icon: '📅',
    keywords: ['booking website', 'reservation site', 'appointments'],
    tags: ['booking website']
  },
  {
    id: 'android-app',
    title: 'Android App',
    description: 'Native Android app development for engaging mobile experiences.',
    href: '/services#app-development',
    group: 'Services',
    category: 'App Development',
    icon: '🤖',
    keywords: ['android app', 'android', 'mobile app'],
    tags: ['android']
  },
  {
    id: 'ios-app',
    title: 'iOS App',
    description: 'Native iOS apps built for elegant performance on Apple devices.',
    href: '/services#app-development',
    group: 'Services',
    category: 'App Development',
    icon: '🍎',
    keywords: ['ios app', 'iOS', 'apple app'],
    tags: ['ios']
  },
  {
    id: 'cross-platform-app',
    title: 'Cross-platform App',
    description: 'Cross-platform apps that reach both Android and iOS users efficiently.',
    href: '/services#app-development',
    group: 'Services',
    category: 'App Development',
    icon: '🌍',
    keywords: ['cross-platform', 'react native', 'flutter', 'mobile app'],
    tags: ['cross-platform']
  },
  {
    id: 'local-seo',
    title: 'Local SEO',
    description: 'Improve local search visibility for nearby customers and storefronts.',
    href: '/services#seo',
    group: 'Services',
    category: 'SEO',
    icon: '📍',
    keywords: ['local seo', 'local search', 'nearby customers'],
    tags: ['local seo']
  },
  {
    id: 'technical-seo',
    title: 'Technical SEO',
    description: 'Technical optimization for faster, more discoverable websites.',
    href: '/services#seo',
    group: 'Services',
    category: 'SEO',
    icon: '⚙️',
    keywords: ['technical seo', 'site speed', 'structured data', 'crawlability'],
    tags: ['technical seo']
  },
  {
    id: 'google-ranking',
    title: 'Google Ranking',
    description: 'SEO strategies focused on improving your ranking in Google search.',
    href: '/services#seo',
    group: 'Services',
    category: 'SEO',
    icon: '📈',
    keywords: ['google ranking', 'search ranking', 'SERP'],
    tags: ['google ranking']
  },
  {
    id: 'website-optimization',
    title: 'Website Optimization',
    description: 'Improve speed, usability, and search visibility for your website.',
    href: '/services#seo',
    group: 'Services',
    category: 'SEO',
    icon: '⚡',
    keywords: ['website optimization', 'performance', 'optimization', 'speed'],
    tags: ['website optimization']
  },
  {
    id: 'training-graphic-design',
    title: 'Graphic Design Training',
    description: 'Learn design fundamentals, layout, and brand systems.',
    href: '/training',
    group: 'Training',
    category: 'Training',
    icon: '🎨',
    keywords: ['graphic design training', 'design course', 'visual systems'],
    tags: ['graphic design', 'training']
  },
  {
    id: 'training-web-development',
    title: 'Web Development Training',
    description: 'Build modern websites and learn the workflow behind web projects.',
    href: '/training',
    group: 'Training',
    category: 'Training',
    icon: '💻',
    keywords: ['web development training', 'coding course', 'frontend', 'backend'],
    tags: ['web development', 'training']
  },
  {
    id: 'training-app-development',
    title: 'App Development Training',
    description: 'Learn how to build mobile apps and app experiences.',
    href: '/training',
    group: 'Training',
    category: 'Training',
    icon: '📱',
    keywords: ['app development training', 'mobile app course'],
    tags: ['app development', 'training']
  },
  {
    id: 'training-ui-ux',
    title: 'UI/UX Training',
    description: 'Master user experience and interface design for premium products.',
    href: '/training',
    group: 'Training',
    category: 'Training',
    icon: '🎯',
    keywords: ['ui/ux training', 'user experience', 'interface design'],
    tags: ['ui/ux', 'training']
  },
  {
    id: 'training-digital-skills',
    title: 'Digital Skills Training',
    description: 'Practical digital skills for modern marketing and online workflows.',
    href: '/training',
    group: 'Training',
    category: 'Training',
    icon: '🧠',
    keywords: ['digital skills', 'productivity training', 'online skills'],
    tags: ['digital skills', 'training']
  },
  {
    id: 'launch-campaign',
    title: 'Launch Campaign',
    description: 'Landing page work designed for conversion and storytelling.',
    href: '/portfolio',
    group: 'Portfolio',
    category: 'Project',
    icon: '🚀',
    keywords: ['launch campaign', 'portfolio project', 'landing page'],
    tags: ['landing page', 'portfolio']
  },
  {
    id: 'client-portal',
    title: 'Client Portal',
    description: 'Dashboard and management experience built for Atlas.',
    href: '/portfolio',
    group: 'Portfolio',
    category: 'Project',
    icon: '📊',
    keywords: ['client portal', 'dashboard project', 'management interface'],
    tags: ['dashboard', 'portfolio']
  },
  {
    id: 'restaurant-experience',
    title: 'Restaurant Experience',
    description: 'Modern restaurant website with menu and booking flow.',
    href: '/portfolio',
    group: 'Portfolio',
    category: 'Project',
    icon: '🍽️',
    keywords: ['restaurant website', 'food', 'dining', 'menu'],
    tags: ['restaurant', 'portfolio']
  },
  {
    id: 'school-network',
    title: 'School Network',
    description: 'School website built for admissions, courses and campus events.',
    href: '/portfolio',
    group: 'Portfolio',
    category: 'Project',
    icon: '🎒',
    keywords: ['school website', 'education', 'campus'],
    tags: ['school', 'portfolio']
  },
  {
    id: 'brand-refresh',
    title: 'Brand Refresh',
    description: 'Brand identity and marketing system for a creative studio.',
    href: '/portfolio',
    group: 'Portfolio',
    category: 'Project',
    icon: '🎯',
    keywords: ['brand refresh', 'identity', 'creative studio'],
    tags: ['brand', 'portfolio']
  },
  {
    id: 'mobile-dashboard',
    title: 'Mobile Dashboard',
    description: 'Responsive mobile dashboard for real-time business operations.',
    href: '/portfolio',
    group: 'Portfolio',
    category: 'Project',
    icon: '📱',
    keywords: ['mobile dashboard', 'admin app', 'business operations'],
    tags: ['dashboard', 'portfolio']
  },
  {
    id: 'dashboard',
    title: 'Dashboard',
    description: 'Your project workspace for orders, messages, files and payments.',
    href: '/dashboard',
    group: 'Dashboard',
    category: 'Dashboard',
    icon: '📂',
    keywords: ['dashboard', 'workspace', 'orders', 'projects', 'messages', 'files', 'payments', 'settings'],
    tags: ['dashboard']
  },
  {
    id: 'orders',
    title: 'Orders',
    description: 'Track all project orders and their delivery status.',
    href: '/dashboard/orders',
    group: 'Dashboard',
    category: 'Dashboard',
    icon: '🧾',
    keywords: ['orders', 'order tracking', 'requests'],
    tags: ['orders']
  },
  {
    id: 'projects',
    title: 'Projects',
    description: 'Review your active and completed projects in one place.',
    href: '/dashboard/projects',
    group: 'Dashboard',
    category: 'Dashboard',
    icon: '📁',
    keywords: ['projects', 'project management', 'tasks'],
    tags: ['projects']
  },
  {
    id: 'messages',
    title: 'Messages',
    description: 'Open messages from your designer and project team.',
    href: '/dashboard/messages',
    group: 'Dashboard',
    category: 'Dashboard',
    icon: '💬',
    keywords: ['messages', 'chat', 'communications'],
    tags: ['messages']
  },
  {
    id: 'files',
    title: 'Files',
    description: 'Upload and download project assets and reference files.',
    href: '/dashboard/files',
    group: 'Dashboard',
    category: 'Dashboard',
    icon: '📦',
    keywords: ['files', 'uploads', 'downloads'],
    tags: ['files']
  },
  {
    id: 'payments',
    title: 'Payments',
    description: 'Review secure Paystack payments and completed invoices.',
    href: '/dashboard/payments',
    group: 'Dashboard',
    category: 'Dashboard',
    icon: '💳',
    keywords: ['payments', 'paystack', 'invoice', 'billing'],
    tags: ['payments']
  },
  {
    id: 'settings',
    title: 'Settings',
    description: 'Manage account preferences, profile details and security.',
    href: '/dashboard/settings',
    group: 'Dashboard',
    category: 'Dashboard',
    icon: '⚙️',
    keywords: ['settings', 'account', 'preferences', 'security'],
    tags: ['settings']
  }
]

export const POPULAR_SEARCHES = [
  'flyer',
  'website',
  'SEO',
  'training',
  'payment',
  'dashboard',
  'portfolio',
  'contact'
]
