export const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || 'http://localhost:3000'
export const SITE_NAME = 'The Odun Design'
export const DEFAULT_OG_IMAGE = `${SITE_URL}/assets/og-image.jpg`
export const TWITTER_HANDLE = '@theodundesign'
export const CONTACT_EMAIL = 'theodundesign@gmail.com'
export const CONTACT_PHONE = '+2348160191823'
export const FACEBOOK_URL = 'https://facebook.com/theodundesign'
export const LINKEDIN_URL = 'https://linkedin.com/company/theodundesign'
export const INSTAGRAM_URL = 'https://instagram.com/theodundesign'
